In [54]:
#series in python pandas and basics stuffs
import numpy as np
import pandas as pd

my_array=np.array([11,22,33])
list= [10,20,30]
label1=[1,2,3]
label2=['a','b','c']
print(pd.Series(my_array,index=label1))
print(pd.Series(list,index=label2))
print(pd.Series(my_array,index=label2))

1    11
2    22
3    33
dtype: int64
a    10
b    20
c    30
dtype: int64
a    11
b    22
c    33
dtype: int64

## DataFrames are series arranged in multiples column (lets move forward...)
```
1 Creating a dataframe 
2.Selection and indexing of Columns 
3.creating a new column 
4.Removing Columns 
5.Selecting Rows
6.Selecting of Rows and Columns 
7.Conditional selections 
```

In [55]:
#CREATING A DATAFRAME USING DICTIONARY
DATA=  {"NAME": ['John','Anna','Peter','Linda'],
        "AGE": [26,34,23,24],
        "SALARY": [30000,40500,23000,12000],
        "CITY": ["Newyork","Paris","Berlin","London"]}
k=pd.DataFrame(DATA)
k

#CREATING A DATAFRAME USING LIST BUT DRAW BACK IS THAT WE NEED TO PUT THE COLUMNS MANUALLY
LIST = [
    ['John', 26, 30000, 'Newyork'],
    ['Anna', 34, 40500, 'Paris'],
    ['Peter', 23, 23000, 'Berlin'],
    ['Linda', 24, 12000, 'London']
]

DF = pd.DataFrame(LIST, columns=["NAME","AGE","SALARY","CITY"])
DF

    NAME  AGE  SALARY     CITY
0   John   26   30000  Newyork
1   Anna   34   40500    Paris
2  Peter   23   23000   Berlin
3  Linda   24   12000   London

In [56]:
#Selection and indexing in datframe of the colums 
print(f"{DF["NAME"]}") #one column
print("===================================")
#for multiple columns 
print(f"{DF[["NAME","AGE"]]}")
#adding of colums 
DF["Designation"]=["HR","ENGINEER","DOCTOR","ENGLISH"]
# DF["DESIGNATION"]=["HR","ENGINEER","DOCTOR","ENGLISH"]
print(DF)
# deleting a column
DF.drop('Designation',axis=1)

0     John
1     Anna
2    Peter
3    Linda
Name: NAME, dtype: object
===================================
    NAME  AGE
0   John   26
1   Anna   34
2  Peter   23
3  Linda   24
    NAME  AGE  SALARY     CITY Designation
0   John   26   30000  Newyork          HR
1   Anna   34   40500    Paris    ENGINEER
2  Peter   23   23000   Berlin      DOCTOR
3  Linda   24   12000   London     ENGLISH

    NAME  AGE  SALARY     CITY
0   John   26   30000  Newyork
1   Anna   34   40500    Paris
2  Peter   23   23000   Berlin
3  Linda   24   12000   London

In [57]:
#for selecting a row 
print(DF)
print(" \n ")
DF.loc[[0,1]]

    NAME  AGE  SALARY     CITY Designation
0   John   26   30000  Newyork          HR
1   Anna   34   40500    Paris    ENGINEER
2  Peter   23   23000   Berlin      DOCTOR
3  Linda   24   12000   London     ENGLISH

   NAME  AGE  SALARY     CITY Designation
0  John   26   30000  Newyork          HR
1  Anna   34   40500    Paris    ENGINEER

In [58]:
DF.iloc[[0]]

   NAME  AGE  SALARY     CITY Designation
0  John   26   30000  Newyork          HR

``SELECTING THE SUBSET OF ROWs and column``

In [59]:

DF

    NAME  AGE  SALARY     CITY Designation
0   John   26   30000  Newyork          HR
1   Anna   34   40500    Paris    ENGINEER
2  Peter   23   23000   Berlin      DOCTOR
3  Linda   24   12000   London     ENGLISH

In [60]:
#selecting the subset of the first 2 rows and 2 columns from the last
DF.loc[[0,1]][['CITY','NAME']]

      CITY  NAME
0  Newyork  John
1    Paris  Anna

`conditional selection`

In [64]:
#i want to see the people ehose age is abov 23
DF[(DF["AGE"] > 23) & (DF["CITY"] == "Paris")]

   NAME  AGE  SALARY   CITY Designation
1  Anna   34   40500  Paris    ENGINEER