## MERGING AND CONCATENATION

```Merging all part```

In [6]:
import numpy as np 
import pandas as pd

#1st dataframe
Employees=pd.DataFrame({
    'Emp_id':[1,2,3,4,5],
    'Emp_name':['Jagat','Sagnik','Ankit','Joydeep','Harshit'],
    'Department':['Senior Developer','Ml-senior Director','Supervisior','Backend Senior Developer','Supervisior']
})
#2nd dataframe
salary=pd.DataFrame({
    'Emp_id':[1,2,3,6,7],
    'Salary':[100000,120000,96000,100000,92000],
    'Bonus':[5000,3200,4500,2000,3400]
})
Employees

   Emp_id Emp_name                Department
0       1    Jagat          Senior Developer
1       2   Sagnik        Ml-senior Director
2       3    Ankit               Supervisior
3       4  Joydeep  Backend Senior Developer
4       5  Harshit               Supervisior

In [7]:
salary

   Emp_id  Salary  Bonus
0       1  100000   5000
1       2  120000   3200
2       3   96000   4500
3       6  100000   2000
4       7   92000   3400

In [8]:
#merging 
pd.merge(Employees,salary)#ondefault it take how ='inner'

   Emp_id Emp_name          Department  Salary  Bonus
0       1    Jagat    Senior Developer  100000   5000
1       2   Sagnik  Ml-senior Director  120000   3200
2       3    Ankit         Supervisior   96000   4500

In [9]:
pd.merge(Employees,salary,how='inner')

   Emp_id Emp_name          Department  Salary  Bonus
0       1    Jagat    Senior Developer  100000   5000
1       2   Sagnik  Ml-senior Director  120000   3200
2       3    Ankit         Supervisior   96000   4500

In [10]:
pd.merge(Employees,salary,how='outer')#it joins on basis of columns and make the places nan where the fields  are empty

   Emp_id Emp_name                Department    Salary   Bonus
0       1    Jagat          Senior Developer  100000.0  5000.0
1       2   Sagnik        Ml-senior Director  120000.0  3200.0
2       3    Ankit               Supervisior   96000.0  4500.0
3       4  Joydeep  Backend Senior Developer       NaN     NaN
4       5  Harshit               Supervisior       NaN     NaN
5       6      NaN                       NaN  100000.0  2000.0
6       7      NaN                       NaN   92000.0  3400.0

In [12]:
pd.merge(Employees,salary,how='left')#joins on basis of employees

   Emp_id Emp_name                Department    Salary   Bonus
0       1    Jagat          Senior Developer  100000.0  5000.0
1       2   Sagnik        Ml-senior Director  120000.0  3200.0
2       3    Ankit               Supervisior   96000.0  4500.0
3       4  Joydeep  Backend Senior Developer       NaN     NaN
4       5  Harshit               Supervisior       NaN     NaN

In [14]:
pd.merge(Employees,salary,how='right')#on the basis of salary

   Emp_id Emp_name          Department  Salary  Bonus
0       1    Jagat    Senior Developer  100000   5000
1       2   Sagnik  Ml-senior Director  120000   3200
2       3    Ankit         Supervisior   96000   4500
3       6      NaN                 NaN  100000   2000
4       7      NaN                 NaN   92000   3400

```concatenation```

In [16]:
#dataframe
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C3']
})
#dataframe 2
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C3

In [18]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [20]:
pd.concat([df1,df2])#dafault concat columnwise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [24]:
pd.concat([df1,df2],axis=1)#row concat columnwise axis=1

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C3  A5  B5  C5

```Joining```

In [31]:
df3=pd.DataFrame({'Name':["Alice","Bob","joye"]},index=[1,2,3])
df4=pd.DataFrame({'Salary':[10000,9000,8000]},index=[2,3,4])
df3

    Name
1  Alice
2    Bob
3   joye

In [28]:
df4

   Salary
2   10000
3    9000
4    8000

In [34]:
df3.join(df4)#default it takes inner

    Name   Salary
1  Alice      NaN
2    Bob  10000.0
3   joye   9000.0

In [35]:
df3.join(df4,how='outer')#now outer will take it all

    Name   Salary
1  Alice      NaN
2    Bob  10000.0
3   joye   9000.0
4    NaN   8000.0