```MISSING DATA MANIPLULATION```

In [1]:
import numpy as np
import pandas as pd

In [5]:
DATA={'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(DATA)

### missing data evaluation

In [7]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [8]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()
# count the number of missing value in each column and give the value

A    1
B    1
C    2
D    3
dtype: int64

In [10]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

### Removing missing value

In [12]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

In [ ]:
values={'A':0,'B':100,"C":1000,"D":10000}
df.fillna(values)#agar yaha pe inplace true likh dunga toh main data mai changes aa jayenge

     A      B       C        D
0  1.0  100.0     1.0      1.0
1  2.0    2.0     2.0  10000.0
2  0.0    3.0     3.0  10000.0
3  4.0    4.0  1000.0  10000.0
4  5.0    5.0  1000.0      5.0