# we are looking to operations that can be done in python

In [2]:
import numpy as np
import pandas as pd

In [3]:
Data={
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[11,12,13,14,15]
}
df=pd.DataFrame(Data)
df

   A   B   C
0  1  10  11
1  2  20  12
2  3  30  13
3  4  40  14
4  5  50  15

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [5]:
df.describe()

              A          B          C
count  5.000000   5.000000   5.000000
mean   3.000000  30.000000  13.000000
std    1.581139  15.811388   1.581139
min    1.000000  10.000000  11.000000
25%    2.000000  20.000000  12.000000
50%    3.000000  30.000000  13.000000
75%    4.000000  40.000000  14.000000
max    5.000000  50.000000  15.000000

In [7]:
df['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [11]:
def Square (x):
    return x*x


df['D']=df['B'].apply(Square)
df

   A   B   C     D
0  1  10  11   100
1  2  20  12   400
2  3  30  13   900
3  4  40  14  1600
4  5  50  15  2500

In [13]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')