## Pivot Tables

In [1]:
import numpy as np
import pandas as pd

In [8]:

data={'Date':pd.date_range('2023-04-01',periods=20),
'Product':['A','B','C','D','E']*4,
'Region':[ 'East','west','North','South','East','west','North','South','East','west','North','South','East','west','North','South','East','west','North','South'],
'Sales':np.random.randint(10,1000,20),
'Units':np.random.randint(10,100,20),
'Rep':['John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice']
}
df=pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-04-01       A   East    871     31   John
1  2023-04-02       B   west    544     89   Mary
2  2023-04-03       C  North    794     36    Bob
3  2023-04-04       D  South     77     21  Alice
4  2023-04-05       E   East    589     72   John
5  2023-04-06       A   west    190     52   Mary
6  2023-04-07       B  North    313     61    Bob
7  2023-04-08       C  South    188     56  Alice
8  2023-04-09       D   East    451     73   John
9  2023-04-10       E   west    641     33   Mary
10 2023-04-11       A  North    244     11    Bob
11 2023-04-12       B  South     33     50  Alice
12 2023-04-13       C   East    126     98   John
13 2023-04-14       D   west    837     91   Mary
14 2023-04-15       E  North     60     45    Bob
15 2023-04-16       A  South     51     40  Alice
16 2023-04-17       B   East    334     93   John
17 2023-04-18       C   west    701     89   Mary
18 2023-04-19       D  North     13     61    Bob
19 2023-04-20       E  South    971     80  Alice

In [10]:
df['month']=df['Date'].dt.month_name()
df

         Date Product Region  Sales  Units    Rep  month
0  2023-04-01       A   East    871     31   John  April
1  2023-04-02       B   west    544     89   Mary  April
2  2023-04-03       C  North    794     36    Bob  April
3  2023-04-04       D  South     77     21  Alice  April
4  2023-04-05       E   East    589     72   John  April
5  2023-04-06       A   west    190     52   Mary  April
6  2023-04-07       B  North    313     61    Bob  April
7  2023-04-08       C  South    188     56  Alice  April
8  2023-04-09       D   East    451     73   John  April
9  2023-04-10       E   west    641     33   Mary  April
10 2023-04-11       A  North    244     11    Bob  April
11 2023-04-12       B  South     33     50  Alice  April
12 2023-04-13       C   East    126     98   John  April
13 2023-04-14       D   west    837     91   Mary  April
14 2023-04-15       E  North     60     45    Bob  April
15 2023-04-16       A  South     51     40  Alice  April
16 2023-04-17       B   East    334     93   John  April
17 2023-04-18       C   west    701     89   Mary  April
18 2023-04-19       D  North     13     61    Bob  April
19 2023-04-20       E  South    971     80  Alice  April

In [13]:
df['Quater']='Q'+df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep  month Quater
0  2023-04-01       A   East    871     31   John  April     Q2
1  2023-04-02       B   west    544     89   Mary  April     Q2
2  2023-04-03       C  North    794     36    Bob  April     Q2
3  2023-04-04       D  South     77     21  Alice  April     Q2
4  2023-04-05       E   East    589     72   John  April     Q2
5  2023-04-06       A   west    190     52   Mary  April     Q2
6  2023-04-07       B  North    313     61    Bob  April     Q2
7  2023-04-08       C  South    188     56  Alice  April     Q2
8  2023-04-09       D   East    451     73   John  April     Q2
9  2023-04-10       E   west    641     33   Mary  April     Q2
10 2023-04-11       A  North    244     11    Bob  April     Q2
11 2023-04-12       B  South     33     50  Alice  April     Q2
12 2023-04-13       C   East    126     98   John  April     Q2
13 2023-04-14       D   west    837     91   Mary  April     Q2
14 2023-04-15       E  North     60     45    Bob  April     Q2
15 2023-04-16       A  South     51     40  Alice  April     Q2
16 2023-04-17       B   East    334     93   John  April     Q2
17 2023-04-18       C   west    701     89   Mary  April     Q2
18 2023-04-19       D  North     13     61    Bob  April     Q2
19 2023-04-20       E  South    971     80  Alice  April     Q2

In [15]:
pd.pivot_table(df,values='Sales',index="Region",columns='Product')

Product      A      B      C      D      E
Region
East     871.0  334.0  126.0  451.0  589.0
North    244.0  313.0  794.0   13.0   60.0
South     51.0   33.0  188.0   77.0  971.0
west     190.0  544.0  701.0  837.0  641.0

In [19]:
pd.pivot_table(df,values="Units",index="Region",columns='Product',aggfunc='median')

Product     A     B     C     D     E
Region
East     31.0  93.0  98.0  73.0  72.0
North    11.0  61.0  36.0  61.0  45.0
South    40.0  50.0  56.0  21.0  80.0
west     52.0  89.0  89.0  91.0  33.0

In [21]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns='Product',aggfunc='median')

         Sales                             Units
Product      A      B      C      D      E     A     B     C     D     E
Region
East     871.0  334.0  126.0  451.0  589.0  31.0  93.0  98.0  73.0  72.0
North    244.0  313.0  794.0   13.0   60.0  11.0  61.0  36.0  61.0  45.0
South     51.0   33.0  188.0   77.0  971.0  40.0  50.0  56.0  21.0  80.0
west     190.0  544.0  701.0  837.0  641.0  52.0  89.0  89.0  91.0  33.0

In [24]:
pd.crosstab(df['Units'],df['Region'])

Region  East  North  South  west
Units
11         0      1      0     0
21         0      0      1     0
31         1      0      0     0
33         0      0      0     1
36         0      1      0     0
40         0      0      1     0
45         0      1      0     0
50         0      0      1     0
52         0      0      0     1
56         0      0      1     0
61         0      2      0     0
72         1      0      0     0
73         1      0      0     0
80         0      0      1     0
89         0      0      0     2
91         0      0      0     1
93         1      0      0     0
98         1      0      0     0

In [25]:
pd.crosstab(df['Units'],df['Sales'])

Sales,13,33,51,60,77,126,188,190,244,313,334,451,544,589,641,701,794,837,871,971
Units,,,,,,,,,,,,,,,,,,,,
11,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
40,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
45,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
50,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
52,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
56,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
61,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
89,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
91,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
93,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0